[2024-03-28 12:19:18,798] 96 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8000
 * Running on http://192.168.1.37:8000
[2024-03-28 12:19:18,798] 96 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[2024-03-28 12:20:09,232] 96 werkzeug - INFO - 127.0.0.1 - - [28/Mar/2024 12:20:09] "GET / HTTP/1.1" 200 -
[2024-03-28 12:20:09,323] 96 werkzeug - INFO - 127.0.0.1 - - [28/Mar/2024 12:20:09] "[33mGET /static/styles.css HTTP/1.1[0m" 404 -
[2024-03-28 12:20:27,042] 828 app - ERROR - Exception on /predict [POST]
Traceback (most recent call last):
  File "C:\project\bike_prediction\venv\lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\project\bike_prediction\venv\lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\project\bike_prediction\venv\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\project\bike_prediction\venv\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "app.py", line 19, in predict
    custom_data = CustomData(
TypeError: __init__() got an unexpected keyword argument 'hr'
[2024-03-28 12:20:27,050] 96 werkzeug - INFO - 127.0.0.1 - - [28/Mar/2024 12:20:27] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
